In [1]:
import gym
import time

In [3]:
env = gym.make('MsPacman-v0')
state = env.reset()

In [11]:

features = []

for i in range(10000):
    observation, reward, done, info = env.step(env.action_space.sample())
    
    features.append({
        'observation': observation,
        'reward': reward,
        'done': done,
        'info': info
    })
    

In [13]:
observation = features[0]['observation']
observation.shape

(210, 160, 3)

In [14]:
env.action_space

Discrete(9)

In [44]:
import torch
torch.randn( 5, 5, 5)

tensor([[[-1.0167e+00, -1.3428e+00,  9.7550e-01,  2.0488e-01,  3.7750e-01],
         [ 1.4238e-01,  4.0997e-01,  2.9476e-01, -1.4659e+00,  1.5626e+00],
         [-7.9333e-01,  1.5022e+00, -1.0986e+00,  1.8591e+00, -1.7104e+00],
         [-1.0467e+00, -1.2219e-01, -6.1479e-01,  1.4888e+00, -1.2361e-01],
         [-3.2361e-01,  3.6274e-01, -1.0487e+00, -1.5557e+00, -3.8618e-01]],

        [[-1.4383e+00,  1.1314e+00, -8.4893e-03,  2.0694e+00, -1.3972e+00],
         [ 2.2467e-01,  3.4890e-02, -1.1558e+00, -4.5383e-01, -3.1265e-01],
         [-1.5077e+00, -1.9374e+00, -4.4211e-02,  8.6153e-01,  1.2338e+00],
         [-1.0417e+00,  1.6217e+00, -9.5146e-01, -3.2364e-01, -7.0624e-01],
         [ 5.8568e-01, -3.6565e-01, -3.5351e-01,  7.9534e-01, -3.3801e-02]],

        [[-4.1067e-01, -1.5751e+00,  1.6768e-01, -4.4933e-01, -8.8505e-01],
         [ 1.9979e+00,  2.5518e+00,  6.9400e-01,  1.1354e+00,  1.7771e+00],
         [-1.5344e-01, -3.1889e-01,  1.5390e+00,  3.8257e-01,  1.8771e+00],
        

In [25]:
import torch.nn as nn

m = nn.Conv2d(3, 16, 5)

In [26]:
m(observation)

TypeError: conv2d() received an invalid combination of arguments - got (numpy.ndarray, Parameter, Parameter, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (numpy.ndarray, Parameter, Parameter, tuple, tuple, tuple, int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (numpy.ndarray, Parameter, Parameter, tuple, tuple, tuple, int)


In [40]:
observation.shape

(210, 160, 3)

In [38]:
cv2 = nn.Conv2d(in_channels=1, out_channels=3, kernel_size=5, stride=1)

In [39]:
cv2(torch.tensor(observation))

RuntimeError: Given groups=1, weight of size [3, 1, 5, 5], expected input[1, 210, 160, 3] to have 1 channels, but got 210 channels instead

In [35]:
torch.tensor(observation).shape

torch.Size([210, 160, 3])

In [53]:
from PIL import Image
import numpy as np

In [54]:
image = Image.fromarray(observation)
image.show()

In [107]:
data = []
label = []

r, g, b = image.split()
r_resize_img = np.asarray(np.float32(r) / 255.0)
b_resize_img = np.asarray(np.float32(g) / 255.0)
g_resize_img = np.asarray(np.float32(b) / 255.0)

rgb_resize_img = np.asarray([r_resize_img, b_resize_img, g_resize_img])
# 이렇게 가공한 이미지를 추가한다.
data.append(rgb_resize_img)
# 라벨 (ant: 0, bee: 1)
label.append(i)

In [80]:
observation.shape

(210, 160, 3)

In [108]:
data[0]

array([[[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.89411765, 0.89411765, 0.89411765, ..., 0.89411765,
         0.89411765, 0.89411765],
        [0.89411765, 0.89411765, 0.89411765, ..., 0.89411765,
         0.89411765, 0.89411765],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]],

       [[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.43529412, 0.43529412, 0.43529412, ..., 0.43529412,
         0.43529412, 0.43529412],
        [0.43529412, 0.43529412, 0.43529412, ..., 0.43529412,
         0.43529412, 0.43529412],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0. 

In [105]:
r = observation[:,:,0]
g = observation[:,:,1]
b = observation[:,:,2]
ou = np.asarray([r,g,b])

In [112]:
torch.from_numpy(ou).float()

tensor([[[  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [228., 228., 228.,  ..., 228., 228., 228.],
         [228., 228., 228.,  ..., 228., 228., 228.],
         ...,
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.]],

        [[  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [111., 111., 111.,  ..., 111., 111., 111.],
         [111., 111., 111.,  ..., 111., 111., 111.],
         ...,
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.]],

        [[  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [111., 111., 111.,  ..., 111., 111., 111.],
         [111., 111., 111.,  ..., 111., 111., 111.],
         ...,
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.]]]

In [96]:
data.shape

(3, 210, 160)

In [79]:
data[0][0].shape

(210, 160)

In [64]:
data[0].shape

(3, 210, 160)

In [93]:
cv2 = nn.Conv2d(3,16,5)

In [104]:
import torch.nn.functional as F

cv2(torch.tensor(ou))

RuntimeError: expected scalar type Byte but found Float

In [100]:
import gym
import collections
import random

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

import numpy as np

# Hyperparameters
learning_rate = 0.0005
gamma = 0.98
buffer_limit = 50000
batch_size = 32


class ReplayBuffer():
    def __init__(self):
        self.buffer = collections.deque(maxlen=buffer_limit)

    def put(self, transition):
        self.buffer.append(transition)

    def sample(self, n):
        mini_batch = random.sample(self.buffer, n)
        s_lst, a_lst, r_lst, s_prime_lst, done_mask_lst = [], [], [], [], []

        for transition in mini_batch:
            s, a, r, s_prime, done_mask = transition

            r = s_prime[:, :, 0]
            g = s_prime[:, :, 1]
            b = s_prime[:, :, 2]

            s_prime = np.asarray([r, g, b])

            r = s[:, :, 0]
            g = s[:, :, 1]
            b = s[:, :, 2]

            s = np.asarray([r, g, b])

            s_lst.append(s)
            a_lst.append([a])
            r_lst.append([r])
            s_prime_lst.append(s_prime)
            done_mask_lst.append([done_mask])


        return torch.tensor(s_lst, dtype=torch.float), torch.tensor(a_lst), \
               torch.tensor(r_lst), torch.tensor(s_prime_lst, dtype=torch.float), \
               torch.tensor(done_mask_lst)

    def size(self):
        return len(self.buffer)




class Qnet(nn.Module):
    def __init__(self):
        super(Qnet, self).__init__()
        self.conv1 = nn.Conv2d(3, 16, 5)
        self.bn1 = nn.BatchNorm2d(16)
        self.conv2 = nn.Conv2d(16, 32, 5)
        self.bn2 = nn.BatchNorm2d(32)
        self.conv3 = nn.Conv2d(32, 32, 5)
        self.bn3 = nn.BatchNorm2d(32)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = F.relu(self.conv2(x))
        x = self.conv3(x)
        return x

    def sample_action(self, obs, epsilon):
        obs = torch.tensor(obs)
        out = self.forward(obs)
        coin = random.random()
        if coin < epsilon:
            return random.randint(0, 1)
        else:
            return out.argmax().item()


def train(q, q_target, memory, optimizer):
    for i in range(10):
        s, a, r, s_prime, done_mask = memory.sample(batch_size)


        q_out = q(s)
        q_a = q_out.gather(1, a)
        max_q_prime = q_target(s_prime).max(1)[0].unsqueeze(1)
        target = r + gamma * max_q_prime * done_mask
        loss = F.smooth_l1_loss(q_a, target)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()


def main():
    env = gym.make('MsPacman-v0')
    q = Qnet()
    q_target = Qnet()
    q_target.load_state_dict(q.state_dict())
    memory = ReplayBuffer()

    print_interval = 20
    score = 0.0
    optimizer = optim.Adam(q.parameters(), lr=learning_rate)

    for n_epi in range(10000):
        epsilon = max(0.01, 0.08 - 0.01 * (n_epi / 200))  # Linear annealing from 8% to 1%
        s = env.reset()
        done = False

        while not done:
            state = s

            r = state[:, :, 0]
            g = state[:, :, 1]
            b = state[:, :, 2]

            state = np.asarray([r, g, b])

            a = q.sample_action(state, epsilon)
            s_prime, r, done, info = env.step(a)

            done_mask = 0.0 if done else 1.0
            memory.put((s, a, r / 100.0, s_prime, done_mask))
            s = s_prime

            score += r

            if done:
                break

        if memory.size() > 2000:
            train(q, q_target, memory, optimizer)

        if n_epi % print_interval == 0 and n_epi != 0:
            q_target.load_state_dict(q.state_dict())
            print("n_episode :{}, score : {:.1f}, n_buffer : {}, eps : {:.1f}%".format(
                n_epi, score / print_interval, memory.size(), epsilon * 100))
            score = 0.0
    env.close()


if __name__ == '__main__':
    main()


RuntimeError: expected scalar type Byte but found Float

In [113]:
env._action_set

AttributeError: attempted to get missing private attribute '_action_set'